%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow vnc port 5901"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow vnc port 5801"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow Apache Windows port 17080"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow Nginx Windows port 4080"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow IIS port 80"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow FileZilla FTP port 21"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow FileZilla FTP port 20"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow FileZilla FTP port Range"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow FileZilla Admin port 14147"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow VMWare Server port 6443"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow RPC port Map"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow RPC port EpMap"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="TFTP Application"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="FTP.EXE Application"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="TELNET.EXE Application"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow PostgreSQL port 5432"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow MySQL port 3306"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow SQLServer port 1433"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow Interbase port 3050"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow Dameware port 6129"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow SVNSERVER port 81"
%SystemRoot%\System32\netsh.exe advfirewall firewall delete rule name="Allow TFTP32 Server port 69"


