@echo off

set myID=YW5vbnltb3VzJnl1ZGVuaXNvdiZ5dWRlbmlzb3ZAbWFpbC5ydSYrNzkwNDcwNzExMjUmODgtMTQ3LTE0Ny0xMDcuc2FuLnJ1Jjg4LTE0Ny0xNDctMTA3LnNhbi5ydSZmb3JleGJyYW5kMjAxNSZvbGVnLXNpbCZvbGVnLXNpbCZXaW43DQo=
set manifest=..\ID\mymanifest.newmanifest

call checknewid_e.bat %myID% %manifest%
