== Exponenta Admin pack

*Год,дата выпуска:* 2019

*Copyright:* © New Internet Technology Inc., 2016-2019

*Лицензия:* BSD (Open Source)

*Разрядность:* 32 bit

*Поддерживаемые платформы:* Microsoft Windows XP SP3, Microsoft Windows
7, Microsoft Windows 8.1, Microsoft Windows 10, Windows 2003 Server SP1,
Windows 2008 Server R2, Windows 2012 Server R2, Windows 2016 Server,
Windows 2019 Server,

Админ пак «Экспонента» (Exponenta) представляет собой модульное
средство, выполняющее следующие функции:

. Управление реестром Windows;
. Предоставление удалённого доступа к компьютеру;
. «Жёсткая блокировка» антивирусов и автоматического обновления Windows;
. Активация и дезактивация защиты от программы mimikatz;
. Добавление в компьютер «универсальной учётной записи» для удалённого
доступа;
. Получение внешнего IP адреса компьютера (при помощи запроса к
сторонним сервисам);
. Проверка системной информации о компьютере;
. И многое другое, неочевидное для пользователя.

Функциональность админ пака расширяется плагинами, которые также
являются самостоятельными программными продуктами, переупакованными
автором админ-пака.

Админ-пак устанавливается в каталог %PUB1%\Util (по умолчанию
C:\pub1\Util). Инсталлятор представляет собой Inno Setup EXE файл,
устанавливающий в папку по умолчанию основные скрипты, а также
устанавливающий переменные окружения. Скрипты затем запускаются из
комендной строки. Из соображений безопасности запрещается автозапуск
этих скриптов после установки.

Внимание! Админ пак может быть использован в злонамеренных целях,
например, для написания вредонсной программы-стайлера. Именно поэтому
многие «параноидальные антивирусы», типа Avast Free Antivirus, опознают
дистрибутив с данными скриптами как malware (вредоносное программное
обеспечение), в то время как другие антивирусы (ESET NOD32, Kaspersky
Internet Security) выдают предупреждающее сообщение о возможной его
потенциальной опасности. Автор заявляет, что в дистрибутиве нет и не
может быть по определению вирусов, а злонамеренность в применении
скриптов лежит на пользователе и администраторе, их запускающем. Сами по
себе скрипты также не содержат вредоносного кода.

*_Категория:_* Админ-паки | *_Добавил:_* yudenis | *Теги:* Админ пак,
Exponenta, Windows 7, Windows Server, Windows 10, admin-pack, new
internet technologies, Windows XP SP3
